export let products = [
    {
        id: 1,
        name: "Черный барный стул",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 1800,
        date: "10.01.2021",
        img: ["bar-chair.jpg","bar-chair.jpg","bar-chair.jpg","bar-chair.jpg"],
        rating: 5,
        inStock: true,
        furniture: 'chair',
        brand: 'amado',
        color: '#fff',
        new: true,
        popular: true
    },
    {
        id: 2,
        name: "Черный современный стул",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 1900,
        date: "10.01.2021",
        img: ["black-chair.jpg","black-chair.jpg","black-chair.jpg","black-chair.jpg"],
        rating: 4,
        inStock: true,
        furniture: 'chair',
        brand: 'amado',
        color: '#fff',
        new: false,
        popular: false
    },
    {
        id: 3,
        name: "Стильный современный стул",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 1700,
        date: "10.01.2021",
        img: ["blue-chair.jpg","blue-chair.jpg","blue-chair.jpg","blue-chair.jpg"],
        rating: 3,
        inStock: true,
        furniture: 'chair',
        brand: 'amado',
        color: '#fff',
        new: true,
        popular: true
    },
    {
        id: 4,
        name: "Современный стул",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 900,
        date: "10.01.2021",
        img: ["cafe-chair.jpg","cafe-chair.jpg","cafe-chair.jpg","cafe-chair.jpg"],
        rating: 4,
        inStock: false,
        furniture: 'chair',
        brand: 'amado',
        color: '#fff',
        new: true,
        popular: false
    },
    {
        id: 5,
        name: "Детский стул",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 790,
        date: "10.01.2021",
        img: ["children-chair.jpg","children-chair.jpg","children-chair.jpg","children-chair.jpg"],
        inStock: false,
        furniture: 'chair',
        rating: 0,
        brand: 'ikea',
        color: '#fff',
        new: true,
        popular: true
    },
    {
        id: 6,
        name: "Дизайнерский современный стул",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 1500,
        date: "11.03.2022",
        img: ["design-chair.jpg","design-chair.jpg","design-chair.jpg","design-chair.jpg"],
        rating: 0,
        inStock: false,
        furniture: 'chair',
        brand: 'ikea',
        color: '#fff',
        new: true,
        popular: false
    },
    {
        id: 7,
        name: "Стул ручной работы",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 1500,
        date: "11.03.2022",
        img: ["hand-made-chair.jpg","hand-made-chair.jpg","hand-made-chair.jpg","hand-made-chair.jpg"],
        rating: 4,
        inStock: false,
        furniture: 'chair',
        brand: 'ikea',
        color: '#fff',
        new: true,
        popular: true
    },
    {
        id: 8,
        name: "Cтул для дома",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 2500,
        date: "11.03.2022",
        img: ["home-chair.jpg","home-chair.jpg","home-chair.jpg","home-chair.jpg"],
        rating: 0,
        inStock: false,
        furniture: 'chair',
        brand: 'ikea',
        color: '#fff',
        new: true,
        popular: false
    },
    {
        id: 9,
        name: "синий современный стул",
        descr: "Предмет мебели для сидения одного человека, с опорой для спины с подлокотниками или без них. Разграничение между стулом и креслом - комфортабельность изделия, рабочее кресло при этом может вовсе не отличаться от рабочего стула.",
        price: 3200,
        date: "11.03.2022",
        img: ["office-chair.jpg","office-chair.jpg","office-chair.jpg","office-chair.jpg"],
        rating: 0,
        inStock: false,
        furniture: 'chair',
        brand: 'ikea',
        color: '#fff',
        new: false,
        popular: true
    },
    {
        id: 10,
        name: "Ваза",
        descr: "Ваза — сосуд, предназначенный для практического применения, изготовленный из глины, фарфора, камня, стекла, металла и других материалов.",
        price: 2000,
        date: "11.03.2023",
        img: ["accessories1.jpg","accessories1.jpg","accessories1.jpg","accessories1.jpg"],
        rating: 3,
        inStock: true,
        furniture: 'accessories',
        brand: 'amado',
        color: '#fff',
        new: false,
        popular: false
    },
    {
        id: 11,
        name: "Ваза",
        descr: "Ваза — сосуд, предназначенный для практического применения, изготовленный из глины, фарфора, камня, стекла, металла и других материалов.",
        price: 2000,
        date: "11.03.2023",
        img: ["accessories2.jpg","accessories2.jpg","accessories2.jpg","accessories2.jpg"],
        rating: 4,
        inStock: true,
        furniture: 'accessories',
        brand: 'amado',
        color: '#fff',
        new: false,
        popular: true
    },
    {
        id: 12,
        name: "Ваза",
        descr: "Ваза — сосуд, предназначенный для практического применения, изготовленный из глины, фарфора, камня, стекла, металла и других материалов.",
        price: 2000,
        date: "11.03.2023",
        img: ["accessories3.jpg","accessories3.jpg","accessories3.jpg","accessories3.jpg"],
        rating: 3,
        inStock: true,
        furniture: 'accessories',
        brand: 'amado',
        color: '#fff',
        new: true,
        popular: false
    },
    {
        id: 13,
        name: "Ваза",
        descr: "Ваза — сосуд, предназначенный для практического применения, изготовленный из глины, фарфора, камня, стекла, металла и других материалов.",
        price: 2000,
        date: "11.03.2023",
        img: ["accessories4.jpg","accessories4.jpg","accessories4.jpg","accessories4.jpg"],
        rating: 2,
        inStock: true,
        furniture: 'accessories',
        brand: 'amado',
        color: '#fff',
        new: true,
        popular: false
    },
    {
        id: 14,
        name: "Ваза",
        descr: "Ваза — сосуд, предназначенный для практического применения, изготовленный из глины, фарфора, камня, стекла, металла и других материалов.",
        price: 2000,
        date: "11.03.2023",
        img: ["accessories5.jpg","accessories5.jpg","accessories5.jpg","accessories5.jpg"],
        rating: 4,
        inStock: false,
        furniture: 'accessories',
        brand: 'amado',
        color: '#fff',
        new: true,
        popular: true
    },
    {
        id: 15,
        name: "Ваза",
        descr: "Ваза — сосуд, предназначенный для практического применения, изготовленный из глины, фарфора, камня, стекла, металла и других материалов.",
        price: 2000,
        date: "11.03.2023",
        img: ["accessories6.jpg","accessories6.jpg","accessories6.jpg","accessories6.jpg"],
        rating: 4,
        inStock: true,
        furniture: 'accessories',
        brand: 'amado',
        color: '#fff',
        new: false,
        popular: false
    },
    {
        id: 16,
        name: "Настольная лампа",
        descr: " Настольные светильники придуманы много столетий назад для комфортного чтения, удобства во время письма и, по возможности, сохранения острого зрения.",
        price: 2000,
        date: "11.03.2023",
        img: ["accessories8.jpg","accessories8.jpg","accessories8.jpg","accessories8.jpg"],
        rating: 2,
        inStock: false,
        furniture: 'accessories',
        brand: 'ikea',
        color: '#fff',
        new: true,
        popular: false
    },
    {
        id: 17,
        name: "Кровать",
        descr: " кровать – это предмет домашнего интерьера, который служит удобным ложем для сна. Имеет продолговатую, прямоугольную форму, ножки и две спинки. На ложе кладут матрац, застилают комплектами постельного белья. Чтобы было удобнее, под голову помещают подушку, а укрываются одеялом. Кровати бывают двуспальными, односпальными и полуторками.",
        price: 12000,
        date: "11.03.2023",
        img: ["bed3.jpg","bed3.jpg","bed3.jpg","bed3.jpg"],
        rating: 3,
        inStock: true,
        furniture: 'bed',
        brand: 'ikea',
        color: '#fff',
        new: false,
        popular: true
    },
    {
        id: 18,
        name: "Кровать",
        descr: " кровать – это предмет домашнего интерьера, который служит удобным ложем для сна. Имеет продолговатую, прямоугольную форму, ножки и две спинки. На ложе кладут матрац, застилают комплектами постельного белья. Чтобы было удобнее, под голову помещают подушку, а укрываются одеялом. Кровати бывают двуспальными, односпальными и полуторками.",
        price: 10000,
        date: "11.03.2023",
        img: ["bed4.jpg","bed4.jpg","bed4.jpg","bed4.jpg"],
        rating: 3,
        inStock: true,
        furniture: 'bed',
        brand: 'factory',
        color: '#fff',
        new: true,
        popular: false
    },
    {
        id: 19,
        name: "Кровать",
        descr: " кровать – это предмет домашнего интерьера, который служит удобным ложем для сна. Имеет продолговатую, прямоугольную форму, ножки и две спинки. На ложе кладут матрац, застилают комплектами постельного белья. Чтобы было удобнее, под голову помещают подушку, а укрываются одеялом. Кровати бывают двуспальными, односпальными и полуторками.",
        price: 11000,
        date: "11.03.2023",
        img: ["bed5.jpg","bed5.jpg","bed5.jpg","bed5.jpg"],
        rating: 4,
        inStock: true,
        furniture: 'bed',
        brand: 'factory',
        color: '#fff',
        new: true,
        popular: true
    },
    {
        id: 20,
        name: "Кровать",
        descr: " кровать – это предмет домашнего интерьера, который служит удобным ложем для сна. Имеет продолговатую, прямоугольную форму, ножки и две спинки. На ложе кладут матрац, застилают комплектами постельного белья. Чтобы было удобнее, под голову помещают подушку, а укрываются одеялом. Кровати бывают двуспальными, односпальными и полуторками.",
        price: 9000,
        date: "11.03.2023",
        img: ["bed6.jpg","bed6.jpg","bed6.jpg","bed6.jpg"],
        rating: 4,
        inStock: true,
        furniture: 'bed',
        brand: 'artdeco',
        color: '#fff',
        new: false,
        popular: false
    },
    {
        id: 21,
        name: "Кровать",
        descr: " кровать – это предмет домашнего интерьера, который служит удобным ложем для сна. Имеет продолговатую, прямоугольную форму, ножки и две спинки. На ложе кладут матрац, застилают комплектами постельного белья. Чтобы было удобнее, под голову помещают подушку, а укрываются одеялом. Кровати бывают двуспальными, односпальными и полуторками.",
        price: 15000,
        date: "11.03.2023",
        img: ["bed7.jpg","bed7.jpg","bed7.jpg","bed7.jpg"],
        rating: 3,
        inStock: true,
        furniture: 'bed',
        brand: 'artdeco',
        color: '#030303',
        new: true,
        popular: true      
    },
    {
        id: 22,
        name: "Кровать",
        descr: " кровать – это предмет домашнего интерьера, который служит удобным ложем для сна. Имеет продолговатую, прямоугольную форму, ножки и две спинки. На ложе кладут матрац, застилают комплектами постельного белья. Чтобы было удобнее, под голову помещают подушку, а укрываются одеялом. Кровати бывают двуспальными, односпальными и полуторками.",
        price: 10000,
        date: "11.03.2023",
        img: ["bed8.jpg","bed8.jpg","bed8.jpg","bed8.jpg"],
        rating: 3,
        inStock: true,
        furniture: 'bed',
        brand: 'amado',
        color: '#fff',
        new: true,
        popular: false
    },
];
